name = "puke365-admin"
compatibility_date = "2024-01-01"

[build]
command = "cd admin && npm ci && npm run build"
cwd = "."
watch_dirs = ["admin/src"]

[build.upload]
format = "directory"
dir = "admin/dist"
