import { PokerCharacter, Language } from './types';

export const POKER_CHARACTERS: PokerCharacter[] = [
  // Texas Style
  { id: 0, name: 'Texas Cowboy', style: 'Aggressive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TexasCowboy&backgroundColor=b6e3f4' },
  { id: 1, name: 'Cowgirl', style: 'Aggressive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Cowgirl&backgroundColor=ffdfbf' },
  { id: 2, name: 'Texas Sheriff', style: 'Tight', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sheriff&backgroundColor=c0aede' },
  { id: 3, name: 'Saloon Gambler', style: 'Bluffer', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gambler&backgroundColor=d1d4f9' },
  
  // Casino Style
  { id: 4, name: 'Casino Dealer', style: 'Tight', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dealer&backgroundColor=ffd5dc' },
  { id: 5, name: 'Vegas Hostess', style: 'Balanced', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hostess&backgroundColor=ffdfbf' },
  { id: 6, name: 'High Roller', style: 'Aggressive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=HighRoller&backgroundColor=b6e3f4' },
  { id: 7, name: 'Poker Pro', style: 'Tight-Aggressive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PokerPro&backgroundColor=c0aede' },

  // Poker Player
  { id: 8, name: 'Card Shark', style: 'Aggressive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CardShark&backgroundColor=d1d4f9' },
  { id: 9, name: 'Bluff Master', style: 'Bluffer', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BluffMaster&backgroundColor=ffd5dc' },
  { id: 10, name: 'Tournament Champion', style: 'Balanced', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Champion&backgroundColor=ffdfbf' },
  { id: 11, name: 'Online Grinder', style: 'Tight', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grinder&backgroundColor=b6e3f4' },

  // VIP Style
  { id: 12, name: 'Billionaire', style: 'Loose', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Billionaire&backgroundColor=c0aede' },
  { id: 13, name: 'Celebrity Player', style: 'Loose', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Celebrity&backgroundColor=d1d4f9' },
  { id: 14, name: 'Poker Queen', style: 'Aggressive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PokerQueen&backgroundColor=ffd5dc' },
  { id: 15, name: 'Business Tycoon', style: 'Tight', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tycoon&backgroundColor=ffdfbf' },

  // Unique Characters
  { id: 16, name: 'Hacker', style: 'Analytical', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hacker&backgroundColor=b6e3f4' },
  { id: 17, name: 'Professor', style: 'Tight', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Professor&backgroundColor=c0aede' },
  { id: 18, name: 'Magician', style: 'Bluffer', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Magician&backgroundColor=d1d4f9' },
  { id: 19, name: 'Street Hustler', style: 'Aggressive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hustler&backgroundColor=ffd5dc' },
];

export const LOCALIZATION: Record<Language, Record<string, string>> = {
  en: {
    lobby: 'Lobby',
    tournament: 'Tournament',
    cashGame: 'Cash Game',
    sitAndGo: 'Sit & Go',
    privateTable: 'Private Table',
    stats: 'Stats',
    shop: 'Shop',
    social: 'Social',
    selectCharacter: 'Select Character',
    back: 'Back',
    fold: 'Fold',
    check: 'Check',
    call: 'Call',
    raise: 'Raise',
    allIn: 'All-In',
    chat: 'Chat',
    placeholder: 'Type a message...',
    jackpot: 'JACKPOT',
    playerCount: 'PLAYERS',
    blindLevel: 'BLIND LEVEL',
    pot: 'POT',
    winRate: 'Win Rate',
    handsPlayed: 'Hands Played',
    vpip: 'VPIP',
    pfr: 'PFR',
    level: 'Level',
    buyIn: 'Buy-in',
    prizePool: 'Prize Pool',
    join: 'Join',
    comingSoon: 'Coming Soon',
    balance: 'Balance',
    quickPlay: 'Quick Play',
    fastJoin: 'Fast Join',
    yourStats: 'Your Stats',
    viewAll: 'View All',
    globalJackpot: 'Global Progressive Jackpot',
    casinoLobby: 'Casino Lobby',
    mainEvent: 'Main Event',
    quickJoin: 'Quick Join',
    tableTypes: 'Table Types',
    playerProfile: 'Player Profile',
    jackpotMarquee: 'Jackpot Marquee',
    playNow: 'Play Now',
    joinNow: 'Join Now',
    guaranteed: 'Guaranteed',
    wsopMainEvent: 'WSOP Main Event',
    worldSeries: 'World Series',
    instantAction: 'Instant Action',
    noLimitHoldem: 'No Limit Hold\'em',
    blinds: 'Blinds',
    startsIn: 'Starts in',
    lateReg: 'Late Reg',
    startingNow: 'Starting Now',
    in: 'In',
    highRollerTurbo: 'High Roller Turbo',
    dailyDeepstack: 'Daily Deepstack',
    sundayMillion: 'Sunday Million',
    gtd: 'GTD',
    yourChips: 'Your Chips',
    currentBet: 'Current Bet',
    handEquity: 'Hand Equity',
    currency: '分',
    totalProfit: 'Total Profit',
    table: 'Table',
    bet: 'BET',
    eq: 'EQ',
    nextLevelIn: 'Next Level In',
    liveNow: 'LIVE NOW',
    sixMaxTurbo: '6-MAX TURBO',
    niceHand: 'Nice hand!',
    handHistory: 'Hand History',
    lastWinner: 'Last Winner',
    squeezeCard: 'Squeeze Card',
    dragToReveal: 'Drag to Reveal',
    close: 'Close',
    profitGraphComingSoon: 'Profit Graph Coming Soon',
    goForGold: 'Go for Gold, Go for Glory',
    avatarsAvailable: 'Avatars Available',
    selected: 'SELECTED',
    royalFlush: 'Royal Flush',
    straightFlush: 'Straight Flush',
    fourOfAKind: 'Four of a Kind',
    fullHouse: 'Full House',
    flush: 'Flush',
    straight: 'Straight',
    threeOfAKind: 'Three of a Kind',
    twoPair: 'Two Pair',
    pair: 'Pair',
    highCard: 'High Card',
    everyoneFolded: 'Everyone else folded',
    log_welcome: 'Welcome to Holdem Hub!',
    log_new_hand: 'New Hand Started. Blinds: {{sb}}/{{bb}}',
    log_win: '{{name}} wins {{amount}}{{currency}} with {{hand}}!',
    log_tournament_over: 'Tournament Over! {{name}} is the CHAMPION!',
    welcome_message: 'Welcome to the Tournament of Legends: Hold\'em.',
    // Character Names
    char_0: 'Texas Cowboy',
    char_1: 'Cowgirl',
    char_2: 'Texas Sheriff',
    char_3: 'Saloon Gambler',
    char_4: 'Casino Dealer',
    char_5: 'Vegas Hostess',
    char_6: 'High Roller',
    char_7: 'Poker Pro',
    char_8: 'Card Shark',
    char_9: 'Bluff Master',
    char_10: 'Tournament Champion',
    char_11: 'Online Grinder',
    char_12: 'Billionaire',
    char_13: 'Celebrity Player',
    char_14: 'Poker Queen',
    char_15: 'Business Tycoon',
    char_16: 'Hacker',
    char_17: 'Professor',
    char_18: 'Magician',
    char_19: 'Street Hustler',
    // Styles
    style_aggressive: 'Aggressive',
    style_tight: 'Tight',
    style_bluffer: 'Bluffer',
    style_balanced: 'Balanced',
    style_tight_aggressive: 'Tight-Aggressive',
    style_loose: 'Loose',
    style_analytical: 'Analytical',
  },
  ko: {
    lobby: '로비',
    tournament: '토너먼트',
    cashGame: '캐시 게임',
    sitAndGo: '싯앤고',
    privateTable: '프라이빗 테이블',
    stats: '통계',
    shop: '상점',
    social: '소셜',
    selectCharacter: '캐릭터 선택',
    back: '뒤로',
    fold: '폴드',
    check: '체크',
    call: '콜',
    raise: '레이즈',
    allIn: '올인',
    chat: '채팅',
    placeholder: '메시지를 입력하세요...',
    jackpot: '잭팟',
    playerCount: '플레이어',
    blindLevel: '블라인드 레벨',
    pot: '팟',
    winRate: '승률',
    handsPlayed: '플레이 핸드',
    vpip: 'VPIP',
    pfr: 'PFR',
    level: '레벨',
    buyIn: '바이인',
    prizePool: '총 상금',
    join: '참가',
    comingSoon: '준비 중',
    balance: '잔액',
    quickPlay: '빠른 시작',
    fastJoin: '빠른 참가',
    yourStats: '내 통계',
    viewAll: '모두 보기',
    globalJackpot: '글로벌 프로그레시브 잭팟',
    casinoLobby: '카지노 로비',
    mainEvent: '메인 이벤트',
    quickJoin: '빠른 참가',
    tableTypes: '테이블 종류',
    playerProfile: '플레이어 프로필',
    jackpotMarquee: '잭팟 전광판',
    playNow: '지금 플레이',
    joinNow: '지금 참가',
    guaranteed: '보장',
    wsopMainEvent: 'WSOP 메인 이벤트',
    worldSeries: '월드 시리즈',
    instantAction: '즉시 시작',
    noLimitHoldem: '노 리밋 홀덤',
    blinds: '블라인드',
    startsIn: '시작까지',
    lateReg: '지연 등록',
    startingNow: '지금 시작',
    in: '후',
    highRollerTurbo: '하이 롤러 터보',
    dailyDeepstack: '데일리 딥스택',
    sundayMillion: '선데이 밀리언',
    gtd: '보장',
    yourChips: '내 칩',
    currentBet: '현재 베팅',
    handEquity: '핸드 에퀴티',
    currency: '分',
    totalProfit: '총 수익',
    table: '테이블',
    bet: '베팅',
    eq: 'EQ',
    nextLevelIn: '다음 레벨까지',
    liveNow: '진행 중',
    sixMaxTurbo: '6인 터보',
    niceHand: '좋은 핸드네요!',
    handHistory: '핸드 히스토리',
    lastWinner: '최근 우승자',
    squeezeCard: '카드 쪼이기',
    dragToReveal: '드래그하여 공개',
    close: '닫기',
    profitGraphComingSoon: '수익 그래프 준비 중',
    goForGold: '황금을 향해, 영광을 향해',
    avatarsAvailable: '개의 아바타 사용 가능',
    selected: '선택됨',
    royalFlush: '로열 플러시',
    straightFlush: '스트레이트 플러시',
    fourOfAKind: '포 오브 어 카인드',
    fullHouse: '풀 하우스',
    flush: '플러시',
    straight: '스트레이트',
    threeOfAKind: '쓰리 오브 어 카인드',
    twoPair: '투 페어',
    pair: '원 페어',
    highCard: '하이 카드',
    everyoneFolded: '다른 플레이어 기권',
    log_welcome: '홀덤 허브에 오신 것을 환영합니다!',
    log_new_hand: '새 핸드 시작. 블라인드: {{sb}}/{{bb}}',
    log_win: '{{name}}님이 {{hand}}(으)로 {{amount}}{{currency}}을(를) 획득했습니다!',
    log_tournament_over: '토너먼트 종료! {{name}}님이 챔피언입니다!',
    welcome_message: '전설의 홀덤 토너먼트 방문을 환영 합니다',
    // Character Names
    char_0: '텍사스 카우보이',
    char_1: '카우걸',
    char_2: '텍사스 보안관',
    char_3: '살롱 갬블러',
    char_4: '카지노 딜러',
    char_5: '베가스 호스테스',
    char_6: '하이 롤러',
    char_7: '포커 프로',
    char_8: '카드 샤크',
    char_9: '블러프 마스터',
    char_10: '토너먼트 챔피언',
    char_11: '온라인 그라인더',
    char_12: '억만장자',
    char_13: '셀러브리티 플레이어',
    char_14: '포커 퀸',
    char_15: '비즈니스 타이쿤',
    char_16: '해커',
    char_17: '교수',
    char_18: '마술사',
    char_19: '스트리트 허슬러',
    // Styles
    style_aggressive: '공격적',
    style_tight: '타이트',
    style_bluffer: '블러퍼',
    style_balanced: '밸런스',
    style_tight_aggressive: '타이트-어그레시브',
    style_loose: '루즈',
    style_analytical: '분석적',
  },
  zh: {
    lobby: '大厅',
    tournament: '锦标赛',
    cashGame: '现金赛',
    sitAndGo: '即时赛',
    privateTable: '私人桌',
    stats: '统计',
    shop: '商店',
    social: '社交',
    selectCharacter: '选择角色',
    back: '返回',
    fold: '弃牌',
    check: '让牌',
    call: '跟注',
    raise: '加注',
    allIn: '全下',
    chat: '聊天',
    placeholder: '输入消息...',
    jackpot: '大奖',
    playerCount: '玩家',
    blindLevel: '盲注级别',
    pot: '底池',
    winRate: '胜率',
    handsPlayed: '玩过的手牌',
    vpip: '入池率',
    pfr: '翻前加注率',
    level: '等级',
    buyIn: '买入',
    prizePool: '奖池',
    join: '加入',
    comingSoon: '即将推出',
    balance: '余额',
    quickPlay: '快速开始',
    fastJoin: '快速加入',
    yourStats: '我的统计',
    viewAll: '查看全部',
    globalJackpot: '全球累积大奖',
    casinoLobby: '赌场大厅',
    mainEvent: '主要赛事',
    quickJoin: '快速加入',
    tableTypes: '桌子类型',
    playerProfile: '玩家资料',
    jackpotMarquee: '大奖跑马灯',
    playNow: '立即开始',
    joinNow: '立即加入',
    guaranteed: '保证',
    wsopMainEvent: 'WSOP 主赛事',
    worldSeries: '世界系列赛',
    instantAction: '即时行动',
    noLimitHoldem: '无限额德州扑克',
    blinds: '盲注',
    startsIn: '开始于',
    lateReg: '延迟注册',
    startingNow: '正在开始',
    in: '在',
    highRollerTurbo: '高额赛加速',
    dailyDeepstack: '每日深筹赛',
    sundayMillion: '周日百万赛',
    gtd: '保证',
    yourChips: '你的筹码',
    currentBet: '当前下注',
    handEquity: '手牌胜率',
    currency: '分',
    totalProfit: '总利润',
    table: '牌桌',
    bet: '下注',
    eq: 'EQ',
    nextLevelIn: '距离下一级',
    liveNow: '正在进行',
    sixMaxTurbo: '6人桌加速',
    niceHand: '好牌！',
    handHistory: '牌局历史',
    lastWinner: '上届冠军',
    squeezeCard: '挤牌',
    dragToReveal: '拖动以揭晓',
    close: '关闭',
    profitGraphComingSoon: '利润图即将推出',
    goForGold: '追求黄金，追求荣耀',
    avatarsAvailable: '个头像可用',
    selected: '已选择',
    royalFlush: '皇家同花顺',
    straightFlush: '同花顺',
    fourOfAKind: '四条',
    fullHouse: '葫芦',
    flush: '同花',
    straight: '顺子',
    threeOfAKind: '三条',
    twoPair: '两对',
    pair: '对子',
    highCard: '高牌',
    everyoneFolded: '其他玩家弃牌',
    log_welcome: '欢迎来到德州中心！',
    log_new_hand: '新局开始。盲注：{{sb}}/{{bb}}',
    log_win: '{{name}} 以 {{hand}} 赢得了 {{amount}}{{currency}}！',
    log_tournament_over: '锦标赛结束！{{name}} 是冠军！',
    welcome_message: '欢迎来到传奇德州扑克锦标赛',
    // Character Names
    char_0: '德州牛仔',
    char_1: '女牛仔',
    char_2: '德州警长',
    char_3: '酒馆赌徒',
    char_4: '赌场荷官',
    char_5: '维加斯女招待',
    char_6: '高额玩家',
    char_7: '扑克职业选手',
    char_8: '扑克高手',
    char_9: '诈唬大师',
    char_10: '锦标赛冠军',
    char_11: '在线职业玩家',
    char_12: '亿万富翁',
    char_13: '名人玩家',
    char_14: '扑克女王',
    char_15: '商业大亨',
    char_16: '黑客',
    char_17: '教授',
    char_18: '魔术师',
    char_19: '街头骗子',
    // Styles
    style_aggressive: '激进型',
    style_tight: '稳健型',
    style_bluffer: '诈唬型',
    style_balanced: '平衡型',
    style_tight_aggressive: '紧凶型',
    style_loose: '松散型',
    style_analytical: '分析型',
  },
};
